# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get Volta cache key
        id: volta-toolchain
        run: echo "key=node-$(jq -r '.volta.node' package.json)-yarn-$(jq -r '.volta.yarn' package.json)" >> $GITHUB_OUTPUT
      - name: Use the Volta cache if available
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/volta
          key: ${{ runner.os }}-volta-${{ steps.volta-toolchain.outputs.key }}
      - uses: volta-cli/action@v4

      - name: Print node/npm/yarn versions
        run: |
          echo "Node: $( node -v )"
          echo "NPM: $( npm -v )"
          echo "Yarn: $( yarn -v )"

      - run: yarn install --immutable
      - run: yarn pack
      - run: npm publish package.tgz --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
